### ISSUE TITLE
Render duplicates list

### ISSUE THREAD

**Issue by thecliffparis** [editor-js/checklist#49]
Hi,

Render from HTML duplicates list in the editor.
Here is an example :

```
editor.blocks.renderFromHTML(`<div>  
<ul>
    <li>David 1
      <ul>
        <li>Bulletpoint 1.A</li>
        <li>Bulletpoint 2.A</li>
      </ul>
    </li>
    <li>Erica 2
      <ul>
        <li>Bulletpoint 2.A</li>
        <li>Bulletpoint 2.B</li>
      </ul>
    </li>
  </ul>
</div>`);
```

![image](https://github.com/user-attachments/assets/ebeeaad5-391a-4e03-8b04-6d68ae61f85d)

**Comment by e11sy** [comment]
hey, this repository is deprecated and no longer supported, you can try using https://github.com/editor-js/list tool (it has full functionality of checklist in it)

**Comment by thecliffparis** [comment]
Will do ! thx
